version: "3"

services:
    mongo:
        image: mongo
        container_name: "economy-news-scrapper-mongo"
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "economy-news-scrapper"
        restart: always
        network_mode: "host"
        ports:
            - "3050:3050"
        depends_on:
            - mongo
